### ISSUE TITLE
more pseudo-elements

### ISSUE THREAD

**Issue by chharvey** [chharvey/bangs#18]
currently we have the suffix `-h` for hover, e.g.:
```css
.-td-ul-h:hover,
.-td-ul-h:focus { text-decoration: underline; }
```

Let's add more suffixes for more pseudo-classes, particularly those of UI interest.
Here are some suggestions, but not all of them need to be addressed (I can't imagine needing bangs for some of them).

- generic pseudo-elements
  - [ ] active
- form pseudo-elements
  - [ ] checked
  - [ ] indeterminate
  - [ ] disabled
  - [ ] invalid

see https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes for more
