### ISSUE TITLE
hover and focus styles

### ISSUE THREAD

**Issue by chharvey** [chharvey/bangs#2]
Add bangs for styles to be applied only on `:hover` and `:focus`, similar to print media.

For example, `class="!td:u^"` would apply underline on hover/focus. The less:

```less
.\!td\:u\^ {
  &:hover,
  &:focus {
    .\!td\:u;
    // of course with .\!td\:u { text-decoration: underline; } defined above
  }
}
```

Note that hover and focus styles need not be specified for different media queries. They should be consistent across all devices. (Let alone they are irrelevant for print media.)

Properties with this feature shall be:
- [x] font-style
- [x] font-variant
- [x] font-weight
- [x] text-transform
- [x] text-decoration
- [ ] visibility **scratching this because :hover disabled on invisibile**
