### ISSUE TITLE
vertical margin and padding in vrus

### ISSUE THREAD

**Issue by chharvey** [chharvey/bangs#25]
Instead of using `rem` units, change vertical margin and padding values to units of `var(--vru)`, for example:

```css
.-mt-1  { margin-top: calc(1 * var(--vru)) !important; }
.-mt-2  { margin-top: calc(2 * var(--vru)) !important; }
.-mt-4  { margin-top: calc(4 * var(--vru)) !important; }
.-mt-8  { margin-top: calc(8 * var(--vru)) !important; }
```

 (vru = "vertical rhythm unit")
