### ISSUE TITLE
background-repeat

### ISSUE THREAD

**Issue by chharvey** [chharvey/bangs#26]
https://developer.mozilla.org/en-US/docs/Web/CSS/background-repeat

add new values & multiple value support

```less
.-br-r  { background-repeat: repeat   ; } // shorthand for `repeat    repeat`
.-br-nr { background-repeat: no-repeat; } // shorthand for `no-repeat no-repeat`
.-br-sp { background-repeat: space    ; } // shorthand for `space     space`
.-br-rd { background-repeat: round    ; } // shorthand for `round     round`

.-br-rx  {
  // background-repeat: repeat no-repeat; // HACK fallback
  background-repeat: repeat-x;
}
.-br-ry  {
  // background-repeat: no-repeat repeat; // HACK fallback
  background-repeat: repeat-y;
}
.-br-spx {
  background-repeat: space no-repeat; // HACK fallback
  background-repeat: space-x; // unstandardized
}
.-br-spy {
  background-repeat: no-repeat space; // HACK fallback
  background-repeat: space-y; // unstandardized
}
.-br-rdx {
  background-repeat: round no-repeat; // HACK fallback
  background-repeat: round-x; // unstandardized
}
.-br-rdy {
  background-repeat: no-repeat round; // HACK fallback
  background-repeat: round-y; // unstandardized
}

// .-br-r_r   { background-repeat: repeat repeat   ; }
// .-br-r_nr  { background-repeat: repeat no-repeat; }
.-br-r_sp  { background-repeat: repeat space    ; }
.-br-r_rd  { background-repeat: repeat round    ; }

// .-br-nr_r  { background-repeat: no-repeat repeat   ; }
// .-br-nr_nr { background-repeat: no-repeat no-repeat; }
// .-br-nr_sp { background-repeat: no-repeat space    ; }
// .-br-nr_rd { background-repeat: no-repeat round    ; }

.-br-sp_r  { background-repeat: space repeat   ; }
// .-br-sp_nr { background-repeat: space no-repeat; }
// .-br-sp_sp { background-repeat: space space    ; }
.-br-sp_rd { background-repeat: space round    ; }

.-br-rd_r  { background-repeat: round repeat   ; }
// .-br-rd_nr { background-repeat: round no-repeat; }
.-br-rd_sp { background-repeat: round space    ; }
// .-br-rd_rd { background-repeat: round round    ; }
```
