### ISSUE TITLE
CSS Grid

### ISSUE THREAD

**Issue by chharvey** [chharvey/bangs#28]
https://www.w3.org/TR/css3-grid-layout/

https://css-tricks.com/snippets/css/complete-guide-grid/

```css
.-d-gd {
  display: -ms-grid;
  display:     grid;
}
.-gtc-1o1 {
  -ms-grid-template-columns: 1fr;
      grid-template-columns: 1fr;
}
@media screen and (min-width: 45em) {
  .-gtc-1o2-sG {
    -ms-grid-template-columns: repeat(2, 1fr);
        grid-template-columns: repeat(2, 1fr);
  }
}
```

grid container properties
- [x] `.-gtc`    grid-template-columns (use same values as `column-count`)
- [x] `.-gtr`    grid-template-rows (use same values as `column-count`)
- [x] `.-gcg`    grid-column-gap (use same values as `column-gap`)
- [x] `.-grg`    grid-row-gap (use same values as `column-gap`)

grid item properties
- [ ] `.-gcs`    grid-column-start
- [ ] `.-gce`    grid-column-end
- [ ] `.-gc`    grid-column (if not using `-start` and `-end` above)
- [ ] `.-grs`    grid-row-start
- [ ] `.-gre`    grid-row-end
- [ ] `.-gr`    grid-row (if not using `-start` and `-end` above)
