### ISSUE TITLE
text-indent hanging & each-line

### ISSUE THREAD

**Issue by chharvey** [chharvey/bangs#30]
The modifier keywords `hanging` and `each-line` have been added to the `text-indent` property:

https://drafts.csswg.org/css-text-3/#text-indent-property

suggested values to add (similar to margin):
- [x] 0 `z`
- [ ] 0.5rem `h`
- [ ] 1rem `1`
- [ ] 3rem `3` (0.5in at default 1rem = 16px)
- [ ] 6rem `6` (1in at default 1rem = 16px)

modifiers:
- hanging `_h`
- each-line `_e`

```less
.-ti-z    { text-indent: 0; }
.-ti-z_h  { text-indent: 0 hanging; }
.-ti-z_e  { text-indent: 0 each-line; }
.-ti-z_he { text-indent: 0 hanging each-line; }
.-ti-h    { text-indent: 0.5rem; }
.-ti-h_h  { text-indent: 0.5rem hanging; }
.-ti-h_e  { text-indent: 0.5rem each-line; }
.-ti-h_he { text-indent: 0.5rem hanging each-line; }
.-ti-1    { text-indent: 1rem; }
.-ti-1_h  { text-indent: 1rem hanging; }
.-ti-1_e  { text-indent: 1rem each-line; }
.-ti-1_he { text-indent: 1rem hanging each-line; }
.-ti-3    { text-indent: 3rem; }
.-ti-3_h  { text-indent: 3rem hanging; }
.-ti-3_e  { text-indent: 3rem each-line; }
.-ti-3_he { text-indent: 3rem hanging each-line; }
.-ti-6    { text-indent: 6rem; }
.-ti-6_h  { text-indent: 6rem hanging; }
.-ti-6_e  { text-indent: 6rem each-line; }
.-ti-6_he { text-indent: 6rem hanging each-line; }
```
