### ISSUE TITLE
add list-style-type: {disclosure-open,disclosure-closed}

### ISSUE THREAD

**Issue by chharvey** [chharvey/bangs#39]
https://drafts.csswg.org/css-counter-styles-3/#simple-symbolic

`disclosure-open`, `disclosure-closed`:

> Symbols appropriate for indicating an open or closed disclosure widget, such as the HTML `<details>` element.

```css
.-lst-o { list-style-type: disclosure-open; }
.-lst-x { list-style-type: disclosure-closed; }
```
